# Generated by Django 2.1.1 on 2018-09-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NormalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('public_status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParallelMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParallelProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('public_status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParallelRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_one', models.ManyToManyField(related_name='doc_one', to='subirarchivos.Document')),
                ('doc_two', models.ManyToManyField(related_name='doc_two', to='subirarchivos.Document')),
            ],
        ),
    ]
