# Generated by Django 2.1.1 on 2018-09-28 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subirarchivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parallelproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_parallelproject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parallelproject',
            name='project_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parallelproject',
            name='relations',
            field=models.ManyToManyField(to='subirarchivos.ParallelRelation'),
        ),
        migrations.AddField(
            model_name='parallelmetadata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_parallelmetadata', to='subirarchivos.ParallelProject'),
        ),
        migrations.AddField(
            model_name='normalproject',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_normalproject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalproject',
            name='project_members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalmetadata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_normalMetadata', to='subirarchivos.NormalProject'),
        ),
        migrations.AddField(
            model_name='documentparallelmetadarelation',
            name='metada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parallelmetadata', to='subirarchivos.ParallelMetadata'),
        ),
        migrations.AddField(
            model_name='documentparallelmetadarelation',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='subirarchivos.ParallelRelation'),
        ),
        migrations.AddField(
            model_name='documentnormalmetadatarelation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='subirarchivos.Document'),
        ),
        migrations.AddField(
            model_name='documentnormalmetadatarelation',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='subirarchivos.NormalMetadata'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_document', to='subirarchivos.NormalProject'),
        ),
    ]
